version: "3.7"
services:
  dist:
    image: "docker.pkg.github.com/damlys/webdock/the-web-cloud-app:dist-0.0.0"
    build:
      context: .
      dockerfile: Dockerfile
      target: dist
      args:
      - GITHUB_PACKAGES_TOKEN
      - NPM_TOKEN
  builder:
    image: "docker.pkg.github.com/damlys/webdock/the-web-cloud-app:builder-0.0.0"
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
      - GITHUB_PACKAGES_TOKEN
      - NPM_TOKEN
