version: "2.4"
services:
  http_tester:
    volumes:
      - type: volume
        source: npm_cache
        target: /root/.npm
      - type: bind
        source: ../../docker-images/nodejs-web-server-tester/app
        target: /app

volumes:
  npm_cache:
    driver: local
    name: global_npm_cache
