version: "2"
services:
  fluent_collector:
    depends_on:
    - mongo
    image: ${DOCKER_IMAGE_PREFIX}fluent-collector:${VERSION}
    restart: always
    environment:
    - FC_SHARED_SECRET
    - FC_MONGO_HOST=mongo
    - FC_MONGO_PORT=27017
    - FC_MONGO_USER=${SERVICES_USER}
    - FC_MONGO_PASSWORD=${MONGO_PASSWORD}
    - FC_MONGO_DATABASE=admin
    - FC_MONGO_COLLECTION=logs
    networks:
    - default
    - monitoring_tier
    ports:
    - ${FLUENT_COLLECTOR_PORT}:24284
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  mongo:
    image: mongo:latest
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${SERVICES_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
    - mongo_config:/data/configdb
    - mongo_data:/data/db
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  mongo_express:
    depends_on:
    - mongo
    image: mongo-express:latest
    restart: always
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_ADMINUSERNAME=${SERVICES_USER}
    - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    - ME_CONFIG_BASICAUTH_USERNAME=${SERVICES_USER}
    - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    ports:
    - ${MONGO_EXPRESS_PORT}:8081
    cpu_shares: 256
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

networks:
  monitoring_tier:
    external: true

volumes:
  mongo_config:
    driver: local

  mongo_data:
    driver: local
