version: "3.7"
services:
  dist:
    entrypoint: []
    command: ["bash"]
    env_file:
    - .env
    networks:
    - host
    volumes:
    - type: volume
      source: npm_cache
      target: /var/cache/npm
    - type: bind
      source: .
      target: /app
networks:
  host:
    external: true
volumes:
  npm_cache:
    driver: local
    name: global_npm_cache
