version: "2.4"
services:
  this:
    depends_on:
      - builder
    build:
      context: .
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/webdock/web-client-app:${VERSION:-unreleased}
    command: ["bash"]

  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: 127.0.0.1:5000/webdock/web-client-app:builder-${VERSION:-unreleased}
    command: ["bash"]
    volumes:
      - type: volume
        source: npm_cache
        target: /root/.npm

volumes:
  npm_cache:
    driver: local
    name: global_npm_cache
