version: "2.4"
services:
  jenkins:
    depends_on:
      - docker
      - registry
    image: damlys/webdock-jenkins-master:${VERSION}
    environment:
      DOCKER_HOST: tcp://docker:2375
      REGISTRY_HOST: registry:5000
      CASC_SELF_URL: "${CASC_SELF_URL}"
      CASC_ADMIN_ADDRESS: "${CASC_ADMIN_ADDRESS}"
      CASC_SLAVE_IMAGE: damlys/webdock-jenkins-slave:${VERSION}
      CASC_SLAVE_ENVIRONMENTS: |
        DOCKER_HOST=tcp://127.0.0.1:2375
        REGISTRY_HOST=registry:5000
      CASC_SLAVE_NETWORK: host
    volumes:
      - type: volume
        source: jenkins_data
        target: /var/jenkins_home
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}

  docker:
    depends_on:
      - docker_hub_mirror
      - registry
    image: docker:18.09.0-dind # aka. Docker in Docker
    command: ["--storage-driver=overlay2", "--registry-mirror=http://docker_hub_mirror:5000", "--insecure-registry=registry:5000", "--log-level=error"]
    privileged: true # Docker Swarm stack doesn't support that option!
    volumes:
      - type: volume
        source: docker_data
        target: /var/lib/docker
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}

  docker_hub_mirror:
    image: registry:latest
    environment:
      REGISTRY_LOG_LEVEL: error
      REGISTRY_LOG_FORMATTER: json
      REGISTRY_LOG_ACCESSLOG_DISABLED: "true"
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    volumes:
      - type: volume
        source: docker_hub_mirror_data
        target: /var/lib/registry
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}

  registry:
    image: registry:latest
    environment:
      REGISTRY_LOG_LEVEL: error
      REGISTRY_LOG_FORMATTER: json
      REGISTRY_LOG_ACCESSLOG_DISABLED: "true"
    volumes:
      - type: volume
        source: registry_data
        target: /var/lib/registry
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}

volumes:
  docker_data:
    driver: local
  docker_hub_mirror_data:
    driver: local
  jenkins_data:
    driver: local
  registry_data:
    driver: local
