version: "2"
services:
  http_server:
    image: ${DOCKER_IMAGE_PREFIX}web-client:${VERSION}
    restart: always
    env_file:
    - .env
    environment:
    - WEBCLIENT_VERSION=${VERSION}
    - WEBCLIENT_HTTP_WORKERS_COUNT=5
    cpu_shares: 1024
    mem_limit: 64mb
    memswap_limit: 0
    labels:
    - version=${VERSION}
