version: "2"
services:
  http_server:
    volumes:
    - ./../../images/web-client/app/public/:/opt/app/public/

  assets_builder:
    image: ${DOCKER_IMAGE_PREFIX}web-assets-builder:0.0.1-example
    command: ["sleep", "infinity"]
    volumes:
    - global_npm_cache:/var/cache/npm/
    - ./../../images/web-client/app/:/opt/app/
    working_dir: /opt/app/
    labels:
    - version=${DOCKER_IMAGE_VERSION}

volumes:
  global_npm_cache:
    external: true
