apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1": {
          "username": "",
          "password": "",
          "email": "",
          "auth": "aAbBcCdDeEfFgG=="
        }
      }
    }
