#!/usr/bin/env groovy

node {
    def dockerImage

    stage('Clone repository') {
        checkout scm
    }

    stage('Build') {
        dockerImage = docker.build('damlys/webdock-api-foundation')
    }

    stage('Release') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            dockerImage.push('latest')
        }
    }
}
