#!/usr/bin/env groovy

node {
    checkout scm

    def dockerImage

    stage('Build') {
        dockerImage = docker.build('damlys/webdock-api-foundation')
    }

    stage('Release') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            dockerImage.push('example')
        }
    }
}
