FROM damlys/webdock-web-client-foundation:example
# has user deploy:1000
# has group deploy:1000
# exposes port 80

ENV APP_VERSION="undefined" \
    APP_ENVIRONMENT="prod" \
    APP_DEBUG="off" \
    APP_HTTP_BASIC_AUTH="off" \
    APP_HTTP_BASIC_AUTH_USER="demo" \
    APP_HTTP_BASIC_AUTH_PASSWORD="Secret123" \
    APP_HTTP_WORKERS_COUNT="5" \
    APP_DEFAULT_CHARSET="UTF-8" \
    APP_DEFAULT_LOCALE="en-US" \
    APP_DEFAULT_TIMEZONE="UTC" \
    APP_API_GATEWAY_DSN="http://username:password@127.0.0.1:80"

COPY --chown=deploy:deploy app/public/ /opt/app/public/
COPY bin/entrypoint.bash /usr/local/bin/entrypoint
COPY bin/healthcheck.bash /usr/local/bin/healthcheck
COPY etc/app/env.js.template /etc/opt/app/env.js.template
COPY etc/app/index.html.template /etc/opt/app/index.html.template
COPY etc/nginx/nginx.conf.template /etc/nginx/nginx.conf.template

RUN chmod a+x /usr/local/bin/entrypoint \
&& chmod a+x /usr/local/bin/healthcheck

WORKDIR /opt/app/
ENTRYPOINT ["entrypoint"]
CMD ["--start-http-server"]
HEALTHCHECK --timeout=3s CMD ["healthcheck"]
