version: "3.7"
services:
  workspace:
    volumes:
    - type: bind
      source: .
      target: /workspace
    working_dir: /workspace
    image: "docker.pkg.github.com/damlys/webdock/the-nodejs:sdk-0.0.0"
    entrypoint: []
    command: ["bash"]
    environment:
    - GITHUB_TOKEN
    - NPM_TOKEN
