version: "3.7"
services:
  workspace:
    volumes:
    - type: bind
      source: .
      target: /workspace
    working_dir: /workspace
    image: "127.0.0.1:55000/webdock/the-nodejs:sdk-0.0.0"
    entrypoint: []
    command: ["bash"]
    environment:
    - NPM_TOKEN
    - REGISTRY_TOKEN
