{{- with .Values.httpServer }}
{{- if .ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ $.Release.Name }}-http-server"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    {{- include "the-web-cloud-platform.metaLabels" $ | nindent 4 }}
    app.kubernetes.io/component: "http-server"
  annotations:
    {{- toYaml .ingress.annotations | nindent 4 }}
spec:
  rules:
  {{- range .ingress.hosts }}
  {{- $host := splitList "/" . }}
  - host: "{{ first $host }}"
    http:
      paths:
      - path: "/{{ rest $host | join "/" }}"
        backend:
          serviceName: "{{ $.Release.Name }}-http-server"
          servicePort: http
  {{- end }}
  tls:
    {{- toYaml .ingress.tls | nindent 4 }}
{{- end }}
{{- end }}
