{{- with .Values.httpServer }}
{{- if .ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-http-server-tls"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    {{- include "the-web-cloud-platform.metaLabels" $ | nindent 4 }}
    app.kubernetes.io/name: "the-web-cloud-server"
    app.kubernetes.io/component: "http-server"
type: kubernetes.io/tls
data:
  tls.crt: {{ .ingress.tls.crt | b64enc | quote }}
  tls.key: {{ .ingress.tls.key | b64enc | quote }}
{{- end }}
{{- end }}
