{{- with .Values.httpServer }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-http-server"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    {{- include "the-web-cloud-platform.metaLabels" $ | nindent 4 }}
    app.kubernetes.io/name: "the-web-cloud-server"
    app.kubernetes.io/component: "http-server"
data:
  {{- range $key, $val := .environmentVariables.encoded }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
