{{- with .Values.httpServer }}
{{- if .ingress.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-http-server-htpasswd"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    {{- include "the-web-cloud-platform.metaLabels" $ | nindent 4 }}
    app.kubernetes.io/name: "the-web-cloud-server"
    app.kubernetes.io/component: "http-server"
type: Opaque
data:
  auth: {{ .ingress.basicAuth.htpasswd | b64enc | quote }}
{{- end }}
{{- end }}
