{{- with .Values.tester }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-tester"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    {{- include "the-web-cloud-platform.metaLabels" $ | nindent 4 }}
    app.kubernetes.io/component: "tester"
data:
  {{- range $key, $val := .environmentVariables.encoded }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
