{{- with .Values.tester }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $.Release.Name }}-tester"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    {{- include "the-web-cloud-platform.metaLabels" $ | nindent 4 }}
    app.kubernetes.io/component: "tester"
data:
  {{- if not (hasKey .environmentVariables.decoded "WEBDOCK_TARGET_ENDPOINT") }}
  WEBDOCK_TARGET_ENDPOINT: "http://{{ $.Release.Name }}-http-server:80"
  {{- end }}
  {{- range $key, $val := .environmentVariables.decoded }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
