version: "2.4"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${BACKING_SERVICES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: db0
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "${BACKING_SERVICES_USER}"
      PGADMIN_DEFAULT_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - type: bind
        # https://www.pgadmin.org/docs/pgadmin4/dev/export_import_servers.html
        source: ./pgadmin-servers.json
        # https://www.pgadmin.org/docs/pgadmin4/dev/container_deployment.html#mapped-files-and-directories
        target: /pgadmin4/servers.json
      - type: volume
        source: pgadmin_data
        target: /var/lib/pgadmin
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    ports:
      - ${PGADMIN_PORT}:80

volumes:
  postgres_data:
    driver: local

  pgadmin_data:
    driver: local
