version: "2.4"
services:
  rabbitmq:
    image: rabbitmq:management #:latest
    environment:
      RABBITMQ_DEFAULT_USER: "${BACKING_SERVICES_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
    volumes:
      - type: volume
        source: rabbitmq_data
        target: /var/lib/rabbitmq
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

volumes:
  rabbitmq_data:
    driver: local
