#!/usr/bin/env make

default:
	exit 0

build:
	docker build --no-cache --tag damlys/webdock-web-assets-builder:unreleased ./web-assets-builder/
	docker tag damlys/webdock-web-assets-builder:unreleased damlys/webdock-web-assets-builder:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker build --no-cache --tag damlys/webdock-web-client-foundation:unreleased ./web-client-foundation/
	docker tag damlys/webdock-web-client-foundation:unreleased damlys/webdock-web-client-foundation:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker build --no-cache --tag damlys/webdock-php-web-server-foundation:unreleased ./php-web-server-foundation/
	docker tag damlys/webdock-php-web-server-foundation:unreleased damlys/webdock-php-web-server-foundation:0.0.1-example
	@echo "\e[42m---\e[0m"

	docker build --no-cache --tag damlys/webdock-web-client:unreleased ./web-application-stack/images/web-client/
	docker tag damlys/webdock-web-client:unreleased damlys/webdock-web-client:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker build --no-cache --tag damlys/webdock-web-client-tester:unreleased ./web-application-stack/images/web-client-tester/
	docker tag damlys/webdock-web-client:unreleased damlys/webdock-web-client-tester:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker build --no-cache --tag damlys/webdock-php-web-server:unreleased ./web-application-stack/images/php-web-server/
	docker tag damlys/webdock-php-web-server:unreleased damlys/webdock-php-web-server:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker build --no-cache --tag damlys/webdock-php-web-server-tester:unreleased ./web-application-stack/images/php-web-server-tester/
	docker tag damlys/webdock-php-web-server-tester:unreleased damlys/webdock-php-web-server-tester:0.0.1-example
	@echo "\e[42m---\e[0m"

	docker build --no-cache --tag damlys/webdock-jenkins-master:unreleased ./automation-stack/images/jenkins-master/
	docker tag damlys/webdock-jenkins-master:unreleased damlys/webdock-jenkins-master:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker build --no-cache --tag damlys/webdock-jenkins-slave:unreleased ./automation-stack/images/jenkins-slave/
	docker tag damlys/webdock-jenkins-slave:unreleased damlys/webdock-jenkins-slave:0.0.1-example
	@echo "\e[42m---\e[0m"

	docker build --no-cache --tag damlys/webdock-fluent-collector:unreleased ./monitoring-stack/images/fluent-collector/
	docker tag damlys/webdock-fluent-collector:unreleased damlys/webdock-fluent-collector:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker build --no-cache --tag damlys/webdock-fluent-forwarder:unreleased ./monitoring-stack/images/fluent-forwarder/
	docker tag damlys/webdock-fluent-forwarder:unreleased damlys/webdock-fluent-forwarder:0.0.1-example

push:
	docker push damlys/webdock-web-assets-builder:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker push damlys/webdock-web-client-foundation:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker push damlys/webdock-php-web-server-foundation:0.0.1-example
	@echo "\e[42m---\e[0m"

	docker push damlys/webdock-web-client:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker push damlys/webdock-web-client-tester:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker push damlys/webdock-php-web-server:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker push damlys/webdock-php-web-server-tester:0.0.1-example
	@echo "\e[42m---\e[0m"

	docker push damlys/webdock-jenkins-master:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker push damlys/webdock-jenkins-slave:0.0.1-example
	@echo "\e[42m---\e[0m"

	docker push damlys/webdock-fluent-collector:0.0.1-example
	@echo "\e[42m---\e[0m"
	docker push damlys/webdock-fluent-forwarder:0.0.1-example
