version: "2.4"
services:
  this:
    build:
      context: .
      dockerfile: Dockerfile
    image: 127.0.0.1:5000/webdock/php-web-server-tester:${VERSION:-unreleased}
    command: ["bash"]
    volumes:
      - type: volume
        source: composer_cache
        target: /root/.composer/cache

volumes:
  composer_cache:
    driver: local
    name: global_composer_cache
