version: "3.7"
services:
  http_tester:
    image: ${DOCKER_IMAGE_PREFIX}php-web-server-tester:${VERSION}
    command: ["sleep", "infinity"]
    environment:
      - WEBSERVERTESTER_TESTS_TARGET_URL=http://http_server
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 64mb
        limits:
          cpus: "1.00"
          memory: 1gb
      restart_policy:
        condition: any
        delay: "0"
      labels:
        - version=${VERSION}
    labels:
      - version=${VERSION}
