version: "3.7"
services:
  mailhog:
    image: mailhog/mailhog:latest
    entrypoint: >
      sh -c "
        echo \"${BACKING_SERVICES_USER}:$$(MailHog bcrypt '${MAILHOG_PASSWORD}')\" > /home/mailhog/htpasswd;
        MailHog -auth-file=/home/mailhog/htpasswd
      "
    ports:
      - mode: ingress
        target: 8025
        published: ${MAILHOG_PORT}
        protocol: tcp
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 64mb
        limits:
          cpus: "1.00"
          memory: 1gb
      restart_policy:
        condition: any
        delay: "0"
      labels:
        - version=${VERSION}
    labels:
      - version=${VERSION}
