version: "2.4"
services:
  mailhog:
    image: mailhog/mailhog:latest
    entrypoint: |
      ash -ce "
        echo \"${BACKING_SERVICES_USER}:$$(MailHog bcrypt '${MAILHOG_PASSWORD}')\" > /home/mailhog/htpasswd
        exec MailHog -auth-file=/home/mailhog/htpasswd
      "
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    ports:
      - ${MAILHOG_PORT}:8025
