version: "2.4"
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${BACKING_SERVICES_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - type: volume
        source: mongo_config
        target: /data/configdb
      - type: volume
        source: mongo_data
        target: /data/db
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0

  mongo_express:
    depends_on:
      - mongo
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${BACKING_SERVICES_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${BACKING_SERVICES_USER}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_PASSWORD}"
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    ports:
      - ${MONGO_EXPRESS_PORT}:8081

volumes:
  mongo_config:
    driver: local

  mongo_data:
    driver: local
