version: "2.4"
services:
  redis:
    image: redis:latest
    command: ["--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - type: volume
        source: redis_data
        target: /data
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0

  redis_commander:
    depends_on:
      - redis
    image: rediscommander/redis-commander:latest
    environment:
      HTTP_USER: "${BACKING_SERVICES_USER}"
      HTTP_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_HOSTS: "session:redis:6379:0:${REDIS_PASSWORD},cache:redis:6379:1:${REDIS_PASSWORD}"
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    ports:
      - ${REDIS_COMMANDER_PORT}:8081

volumes:
  redis_data:
    driver: local
