version: "3.7"
services:
  rte:
    image: "docker.pkg.github.com/damlys/webdock/the-nodejs:rte-0.0.0"
    build:
      context: .
      dockerfile: Dockerfile
      target: rte
  sdk:
    image: "docker.pkg.github.com/damlys/webdock/the-nodejs:sdk-0.0.0"
    build:
      context: .
      dockerfile: Dockerfile
      target: sdk
