version: "2"
services:
  migrator:
    image: ${DOCKER_IMAGE_PREFIX}php-web-server:${VERSION}
    command: ["--start-migrator"]
    restart: on-failure
    env_file:
    - .env
    environment:
    - WEBSERVER_VERSION=${VERSION}
    cpu_shares: 1024
    mem_limit: 64mb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  cgi_server:
    depends_on:
    - migrator
    image: ${DOCKER_IMAGE_PREFIX}php-web-server:${VERSION}
    command: ["--start-cgi-server"]
    restart: always
    env_file:
    - .env
    environment:
    - WEBSERVER_VERSION=${VERSION}
    - WEBSERVER_CGI_WORKERS_COUNT=5
    cpu_shares: 1024
    mem_limit: 256mb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  http_server:
    depends_on:
    - cgi_server
    image: ${DOCKER_IMAGE_PREFIX}php-web-server:${VERSION}
    restart: always
    env_file:
    - .env
    environment:
    - WEBSERVER_VERSION=${VERSION}
    - WEBSERVER_CGI_SERVER_HOST=cgi_server
    - WEBSERVER_CGI_SERVER_PORT=9000
    - WEBSERVER_HTTP_WORKERS_COUNT=5
    cpu_shares: 1024
    mem_limit: 64mb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  task_scheduler:
    depends_on:
    - migrator
    image: ${DOCKER_IMAGE_PREFIX}php-web-server:${VERSION}
    command: ["--start-task-scheduler"]
    restart: always
    env_file:
    - .env
    environment:
    - WEBSERVER_VERSION=${VERSION}
    cpu_shares: 1024
    mem_limit: 64mb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  example_worker:
    depends_on:
    - migrator
    image: ${DOCKER_IMAGE_PREFIX}php-web-server:${VERSION}
    command: ["--start-example-worker"]
    restart: always
    env_file:
    - .env
    environment:
    - WEBSERVER_VERSION=${VERSION}
    cpu_shares: 1024
    mem_limit: 64mb
    memswap_limit: 0
    labels:
    - version=${VERSION}
