version: "2"
x-dependencies:
  &dependencies
  depends_on:
  - minio
  - mongo
  - mysql
  - postgres
  - rabbitmq
  - redis

services:
  cgi_server: *dependencies
  example_worker: *dependencies
  migrator: *dependencies
  task_scheduler: *dependencies

  minio:
    image: minio/minio:latest
    command: ["minio", "server", "/data"]
    restart: always
    environment:
    - MINIO_ACCESS_KEY=${BACKING_SERVICES_USER}
    - MINIO_SECRET_KEY=${MINIO_PASSWORD}
    volumes:
    - minio_data:/data
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  minio_constructor:
    depends_on:
    - minio
    image: minio/mc:latest
    entrypoint: >
      sh -c "
        /usr/bin/mc config host add myminioserver http://minio:9000 '${BACKING_SERVICES_USER}' '${MINIO_PASSWORD}';
        /usr/bin/mc mb myminioserver/myminiobucket;
        /usr/bin/mc policy download myminioserver/myminiobucket;
        exit 0
      "
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  mongo:
    image: mongo:latest
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${BACKING_SERVICES_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
    - mongo_config:/data/configdb
    - mongo_data:/data/db
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  mysql:
    image: mysql:5
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_USER=${BACKING_SERVICES_USER}
    - MYSQL_PASSWORD
    - MYSQL_DATABASE=db0
    volumes:
    - mysql_data:/var/lib/mysql
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  postgres:
    image: postgres:latest
    restart: always
    environment:
    - POSTGRES_USER=${BACKING_SERVICES_USER}
    - POSTGRES_PASSWORD
    - POSTGRES_DB=db0
    volumes:
    - postgres_data:/var/lib/postgresql/data
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    environment:
    - RABBITMQ_DEFAULT_USER=${BACKING_SERVICES_USER}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  redis:
    image: redis:latest
    command: ["--requirepass", "${REDIS_PASSWORD}"]
    restart: always
    volumes:
    - redis_data:/data
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

volumes:
  minio_data:
    driver: local

  mongo_config:
    driver: local

  mongo_data:
    driver: local

  mysql_data:
    driver: local

  postgres_data:
    driver: local

  rabbitmq_data:
    driver: local

  redis_data:
    driver: local
