version: "2"
services:
  minio:
    ports:
    - ${MINIO_PORT}:9000

  mongo_express:
    depends_on:
    - mongo
    image: mongo-express:latest
    restart: always
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_ADMINUSERNAME=${BACKING_SERVICES_USER}
    - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    - ME_CONFIG_BASICAUTH_USERNAME=${BACKING_SERVICES_USER}
    - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    ports:
    - ${MONGO_EXPRESS_PORT}:8081
    cpu_shares: 256
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  # pgAdmin and PostgreSQL connection have to be configured manually.
  # Open ${PGADMIN_PORT} in your browser, click RMB on the "Servers",
  # hover "Create" and click "Server...".
  # On the "Connection" tab use the following values:
  # Host: postgres
  # Port: 5432
  # User: ${BACKING_SERVICES_USER}
  # Password: ${POSTGRES_PASSWORD}
  pgadmin:
    depends_on:
    - postgres
    image: dpage/pgadmin4:latest
    restart: always
    environment:
    - PGADMIN_DEFAULT_EMAIL=${BACKING_SERVICES_USER}
    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
    - "${PGADMIN_PORT}:80"
    volumes:
    - pgadmin_config:/var/lib/pgadmin
    cpu_shares: 256
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  phpmyadmin:
    depends_on:
    - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
    ports:
    - ${PHPMYADMIN_PORT}:80
    cpu_shares: 256
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

  rabbitmq:
    image: rabbitmq:management
    ports:
    - ${RABBITMQ_MANAGEMENT_PORT}:15672

  redis_commander:
    depends_on:
    - redis
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - HTTP_USER=${BACKING_SERVICES_USER}
    - HTTP_PASSWORD=${REDIS_PASSWORD}
    - REDIS_HOSTS=session:redis:6379:0:${REDIS_PASSWORD},cache:redis:6379:1:${REDIS_PASSWORD}
    ports:
    - ${REDIS_COMMANDER_PORT}:8081
    cpu_shares: 256
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${VERSION}

volumes:
  pgadmin_config:
    driver: local
