version: "2.4"
x-environments:
  &environments
  WEBSERVER_VERSION: "${VERSION}"
  WEBSERVER_XDEBUG_ENABLE: "${WEBSERVER_XDEBUG_ENABLE-off}"
  WEBSERVER_XDEBUG_REMOTE_AUTOSTART: "${WEBSERVER_XDEBUG_REMOTE_AUTOSTART}"
  WEBSERVER_XDEBUG_REMOTE_CONNECT_BACK: "${WEBSERVER_XDEBUG_REMOTE_CONNECT_BACK}"
  WEBSERVER_XDEBUG_REMOTE_HOST: "${WEBSERVER_XDEBUG_REMOTE_HOST}"
  WEBSERVER_XDEBUG_REMOTE_PORT: "${WEBSERVER_XDEBUG_REMOTE_PORT}"
  WEBSERVER_XDEBUG_IDE_KEY: "${WEBSERVER_XDEBUG_IDE_KEY}"
  WEBSERVER_ENVIRONMENT: "${WEBSERVER_ENVIRONMENT-prod}"
  WEBSERVER_DEBUG: "${WEBSERVER_DEBUG-off}"
  WEBSERVER_CACHE_STORAGE_DSN: "${WEBSERVER_CACHE_STORAGE_DSN}"
  WEBSERVER_DATA_STORAGE_DSN: "${WEBSERVER_DATA_STORAGE_DSN}"
  WEBSERVER_FILE_STORAGE_DSN: "${WEBSERVER_FILE_STORAGE_DSN}"
  WEBSERVER_MAIL_SENDER_URL: "${WEBSERVER_MAIL_SENDER_URL}"
  WEBSERVER_MESSAGE_QUEUE_DSN: "${WEBSERVER_MESSAGE_QUEUE_DSN}"
  WEBSERVER_SESSION_STORAGE_DSN: "${WEBSERVER_SESSION_STORAGE_DSN}"

services:
  migrator:
    image: damlys/webdock-php-web-server:${VERSION}
    command: ["--start-migrator"]
    environment:
      <<: *environments
    scale: 1
    restart: on-failure
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}

  cgi_server:
    depends_on:
      - migrator
    image: damlys/webdock-php-web-server:${VERSION}
    command: ["--start-cgi-server"]
    environment:
      <<: *environments
      WEBSERVER_CGI_WORKERS_COUNT: 5
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}

  http_server:
    depends_on:
      - cgi_server
    image: damlys/webdock-php-web-server:${VERSION}
    environment:
      <<: *environments
      WEBSERVER_CGI_SERVER_HOST: cgi_server
      WEBSERVER_CGI_SERVER_PORT: 9000
      WEBSERVER_HTTP_WORKERS_COUNT: 5
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}

  task_scheduler:
    depends_on:
      - migrator
    image: damlys/webdock-php-web-server:${VERSION}
    command: ["--start-task-scheduler"]
    environment:
      <<: *environments
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}

  example_worker:
    depends_on:
      - migrator
    image: damlys/webdock-php-web-server:${VERSION}
    command: ["--start-example-worker"]
    environment:
      <<: *environments
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}
