version: "2.4"
services:
  http_tester:
    depends_on:
      - http_server
    image: damlys/webdock-php-web-server-tester:${VERSION}
    command: ["sleep", "infinity"]
    environment:
      WEBSERVERTESTER_TESTS_TARGET_URL: http://http_server
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}
