version: "2.4"
services:
  http_tester:
    volumes:
      - type: volume
        source: composer_cache
        target: /root/.composer/cache
      - type: bind
        source: ../../docker-images/php-web-server-tester/app
        target: /app

volumes:
  composer_cache:
    driver: local
    name: global_composer_cache
