version: "2.4"
x-dependencies:
  &dependencies
  depends_on:
    - mailhog

services:
  migrator: *dependencies
  cgi_server: *dependencies
  task_scheduler: *dependencies
  example_worker: *dependencies

  mailhog:
    image: mailhog/mailhog:latest
    entrypoint: >
      ash -c "
        echo \"${BACKING_SERVICES_USER}:$$(MailHog bcrypt '${MAILHOG_PASSWORD}')\" > /home/mailhog/htpasswd;
        MailHog -auth-file=/home/mailhog/htpasswd
      "
    scale: 1
    restart: always
    cpu_shares: 1024
    mem_limit: 1gb
    memswap_limit: 0
    labels:
      - version=${VERSION}
