version: "2.4"
services:
  minio:
    ports:
      - ${MINIO_PORT}:9000

  mongo_express:
    ports:
      - ${MONGO_EXPRESS_PORT}:8081

  pgadmin:
    ports:
      - ${PGADMIN_PORT}:80

  phpmyadmin:
    ports:
      - ${PHPMYADMIN_PORT}:80

  rabbitmq:
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:15672

  redis_commander:
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
