version: "3.7"
services:
  http_server:
    volumes:
      - type: bind
        source: ../../docker-images/web-client/app/public
        target: /opt/app/public

  builder:
    image: damlys/webdock-web-assets-builder:0.0.1-example
    working_dir: /opt/app
    command: ["sleep", "infinity"]
    volumes:
      - type: volume
        source: global_npm_cache
        target: /var/cache/npm
      - type: bind
        source: ../../docker-images/web-client/app
        target: /opt/app
    deploy:
      restart_policy:
        condition: any
        delay: "0"
      labels:
        - version=${VERSION}
    labels:
      - version=${VERSION}

volumes:
  global_npm_cache:
    external: true
