version: "3.7"
services:
  web_tester:
    image: damlys/webdock-web-client-tester:${VERSION}
    command: ["sleep", "infinity"]
    environment:
      - WEBCLIENTTESTER_SELENIUM_HUB_HOST=selenium_hub
      - WEBCLIENTTESTER_SELENIUM_HUB_PORT=4444
      - WEBCLIENTTESTER_TESTS_TARGET_URL=http://http_server
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 64mb
        limits:
          cpus: "1.00"
          memory: 1gb
      restart_policy:
        condition: any
        delay: "0"
      labels:
        - version=${VERSION}
    labels:
      - version=${VERSION}

  selenium_hub:
    image: selenium/hub:latest
    environment:
      - GRID_NEW_SESSION_WAIT_TIMEOUT=60000
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 128mb
        limits:
          cpus: "1.00"
          memory: 1gb
      restart_policy:
        condition: any
        delay: "0"
      labels:
        - version=${VERSION}
    labels:
      - version=${VERSION}

  selenium_chrome:
    image: selenium/node-chrome:latest
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
    entrypoint: bash -c "SE_OPTS=\"-host $$HOSTNAME\" /opt/bin/entry_point.sh"
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 128mb
        limits:
          cpus: "1.00"
          memory: 1gb
      restart_policy:
        condition: any
        delay: "0"
      labels:
        - version=${VERSION}
    labels:
      - version=${VERSION}

  selenium_firefox:
    image: selenium/node-firefox:latest
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
    entrypoint: bash -c "SE_OPTS=\"-host $$HOSTNAME\" /opt/bin/entry_point.sh"
    deploy:
      resources:
        reservations:
          cpus: "0.10"
          memory: 128mb
        limits:
          cpus: "1.00"
          memory: 1gb
      restart_policy:
        condition: any
        delay: "0"
      labels:
        - version=${VERSION}
    labels:
      - version=${VERSION}
