version: "3.7"
services:
  workspace:
    #environment:
    #- FOO=bar
    networks:
    - host
    volumes:
    - type: volume
      source: npm_cache
      target: /var/cache/npm
networks:
  host:
    external: true
volumes:
  npm_cache:
    driver: local
    name: global_npm_cache
