version: "2"
x-dependencies:
  &dependencies
  depends_on:
  - mailhog

services:
  cgi_server: *dependencies
  example_worker: *dependencies
  migrator: *dependencies
  task_scheduler: *dependencies

  mailhog:
    image: mailhog/mailhog:latest
    entrypoint: >
      sh -c "
        echo \"${BACKING_SERVICES_USER}:$$(MailHog bcrypt '${MAILHOG_PASSWORD}')\" > /home/mailhog/htpasswd;
        MailHog -auth-file=/home/mailhog/htpasswd
      "
    restart: on-failure
    ports:
    - ${MAILHOG_PORT}:8025
    cpu_shares: 256
    mem_limit: 1gb
    memswap_limit: 0
    labels:
    - version=${DOCKER_IMAGE_VERSION}
