#!/usr/bin/env groovy

node {
    checkout scm

    def dockerImage

    stage('Build') {
        dockerImage = docker.build('damlys/webdock-php-foundation')
    }

    stage('Test') {
        dockerImage.inside(
            sh 'dpkg --status cron'
            sh 'dpkg --status git'
            sh 'dpkg --status nginx'
            sh 'dpkg --status gettext'

            sh 'php --version'
            sh 'php-fpm --version'
            sh 'composer --version'
        )
    }

    stage('Release') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            dockerImage.push('example')
        }
    }
}
